# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GET TIPS 200 OK
subtitle: ''
description: 'Blog đăng vớ vẩn linh tinh'
keywords:
author: haphuthinh
language: vn
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://gettips200ok.netlify.app/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Sitemap
sitemap:
  path: sitemap.xml

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

#Search
search:
  path: search.json
  field: post
  content: true

hexo_submit_urls_to_search_engine:
  submit_condition: count # Submitted condition, optional value: count | period, Now only supports count
  count: 10 # Submit the latest 10 links
  period: 900 # Submit a link with a modification time of 900 seconds
  google: 1 #  Whether to submit to Google, optional values: 1 | 0 (0: No; 1: Yes)
  bing: 0 #  Whether to submit to bing, optional value: 1 | 0 (0: no; 1: yes)
  baidu: 0 # Whether to submit to baidu, optional value: 1 | 0 (0: no; 1: yes)
  txt_path: submit_urls.txt ## The address of the text document, the link to be pushed will be saved in this text document
  baidu_host: https://cjh0613.github.io ## Domain name registered in Baidu webmaster platform
  baidu_token: xxxxx ## Please note that this is your secret key, so do not publish the website source code in the public repository!
  bing_host: https://cjh0613.github.io ## Domain name registered in Bing webmaster platform
  bing_token: xxxxx ## Please note that this is your secret key, so do not publish the website source code in the public repository!
  google_host: https://gettips200ok.netlify.app/ ## Domain name registered in Google webmaster platform
  google_key_file: google-api.json # Store the json file of the google key in the root directory of the website (same location as the hexo _config.yml file), please do not publish the source code of the website in the public warehouse!
  google_proxy: 0 # Set the proxy used to submit urls to Google
  replace: 0  # Whether to replace some substrings in links, optional value: 1 | 0 (0: no; 1: yes)
  find_what: https://gettips200ok.netlify.app/
  replace_with: https://gettips200ok.netlify.app/

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-cupertino

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: cjh_google_url_submitter
- type: cjh_bing_url_submitter
- type: cjh_baidu_url_submitter

giscus:
  <script src="https://giscus.app/client.js"
          data-repo="chabuuuu/Gitalk-GETTIPS200OK"
          data-repo-id="R_kgDOKh_c4g"
          data-category="General"
          data-category-id="DIC_kwDOKh_c4s4CaPaK"
          data-mapping="pathname"
          data-strict="0"
          data-reactions-enabled="1"
          data-emit-metadata="0"
          data-input-position="bottom"
          data-theme="noborder_gray"
          data-lang="en"
          crossorigin="anonymous"
          async>
  </script>
